{ inputs, ... }:

let
  frameworkModule = {
    imports = [
      inputs.disko.nixosModules.disko
      inputs.impermanence.nixosModules.impermanence
      inputs.sops-nix.nixosModules.sops

      # Generated by nixos-anywhere via `--generate-hardware-config nixos-facter`.
      # See ./README.md for how to (re)generate this.
      { hardware.facter.reportPath = ./facter.json; }
      ./disko.nix
      ./persistence.nix
      ./sops.nix
      ./configuration.nix
    ];
  };
in
{
  flake = {
    # Consumed by private deployment flake
    nixosModules.framework = frameworkModule;

    # Public config using stub
    nixosConfigurations.framework = inputs.nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [ frameworkModule ];
    };
  };
}
