{ inputs, ... }:
{
  flake.nixosConfigurations.framework = inputs.nixpkgs.lib.nixosSystem {
    system = "x86_64-linux";
    specialArgs = { inherit inputs; };
    modules = [
      inputs.disko.nixosModules.disko
      inputs.impermanence.nixosModules.impermanence
      inputs.facter.nixosModules.facter
      # Generated by nixos-anywhere via `--generate-hardware-config nixos-facter`.
      # See ./README.md for how to (re)generate this.
      { facter.reportPath = ./facter.json; }
      ../../modules/nixos/ifox.nix
      ./disko.nix
      ./persistence.nix
      ./sops.nix
      ./configuration.nix
    ];
  };
}
